# Site settings
title:            Menu Akord
email:            greetings@ashliewebb.com
description:      "An accordion-style menu using css3 transitions."
baseurl:          ""
url:              "http://www.ashilewebb.com/menuakord"
author:
  name:           Ashile Webb
  url:            http://www.ashliewebb.com
  email:          greetings@ashliewebb.com
twitter_username: ashlie012
github_username:  ashliewebb

# Build settings
markdown: kramdown
permalink: pretty
